#!/usr/bin/env bash

#========================================
# Generate .pre-commit-config.yaml file
#========================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOL_VERSIONS="${ROOT}/.tool-versions"
OUTPUT="${ROOT}/.pre-commit-config.yaml"
CHECK=false

usage() {
  cat <<EOF
Usage: ${0##*/} [--check]

Options:
  --check  Exit 1 if the .pre-commit-config.yaml file is not up to date
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ ! -f "${TOOL_VERSIONS}" ]]; then
  echo "error: ${TOOL_VERSIONS} not found" >&2
  exit 1
fi

if [[ "${CHECK}" == true && ! -f "${OUTPUT}" ]]; then
  echo "error: ${OUTPUT} not found; run without --check to generate it" >&2
  exit 1
fi

# Get tool version from .tool-versions file
get_version() {
  local name="$1"
  awk -v name="${name}" '$1 == name { print $2; exit }' "${TOOL_VERSIONS}"
}

# Repo definitions
# Format: <tool-name>|<repo-url>|<hook-id>|<rev-prefix>
REPO_DEFS=(
  'markdownlint-cli2|https://github.com/DavidAnson/markdownlint-cli2|markdownlint-cli2|v'
)

generate() {
  cat <<'HEADER'
# Generated by scripts/generate-pre-commit-config.sh
# DO NOT EDIT - update .tool-versions and re-run the script.
repos:
HEADER

  for def in "${REPO_DEFS[@]}"; do
    IFS='|' read -r tool repo hook_id rev_prefix <<< "${def}" || true

    version="$(get_version "${tool}")"
    if [[ -z "${version}" ]]; then
      echo "error: ${tool} not found in .tool-versions" >&2
      exit 1
    fi

    cat <<EOF
  - repo: ${repo}
    rev: ${rev_prefix}${version}
    hooks:
      - id: ${hook_id}
EOF
  done
}

if [[ "${CHECK}" == true ]]; then
  tmp="$(mktemp)"
  trap 'rm -f "${tmp}"' EXIT
  generate > "${tmp}"
  if cmp -s "${OUTPUT}" "${tmp}"; then
    exit 0
  else
    echo "error: .pre-commit-config.yaml is out of sync with .tool-versions" >&2
    diff -u "${OUTPUT}" "${tmp}" >&2 || true
    exit 1
  fi
else
  generate > "${OUTPUT}"
  echo "Generated ${OUTPUT} successfully"
fi
